### ISSUE TITLE
Renamer \u0000

### ISSUE THREAD

**Issue by lolka13372** [ItzSomebody/Radon#77]
I am trying to use StopDecompilingMyJava/Entry-003 and get 
![image](https://user-images.githubusercontent.com/51010014/58425770-5d02cd00-80a3-11e9-8b81-8fca53c12072.png)
In your Renamer, I write META-INF/ \u0000/ maybe it should work differently please help me

**Comment by ItzSomebody** [comment]
Using
```yaml
renamer:
  adapt_these_resources:
    - ".*"
  repackage_name: "META-INF/\u0000"
```
worked fine for me. What version of Radon is this?
