### ISSUE TITLE
Setting exclusions hangs renamer

### ISSUE THREAD

**Issue by ItzSomebody** [ItzSomebody/Radon#79]
**Description of Bug:** See title (specifically hangs on the "Applying mappings" stage).

**Expected behavior:** Not to hang.

**Radon version:** Commit b9c4ae9ea1d58bcd4b765417cb5c2576fb353710

**Configuration:** 

```yaml
input: "Counter.jar"
output: "Counter-OBF.jar"
shrinker:
  remove_deprecated: true
  remove_inner_classes: true
  remove_invisible_annotations: true
  remove_invisible_parameter_annotations: true
  remove_invisible_type_annotations: true
  remove_line_numbers: true
  remove_local_variables: true
  remove_outer_method: true
  remove_signature: true
  remove_source_debug: true
  remove_source_file: true
  remove_synthetic: true
  remove_unknown_attributes: true
  remove_visible_annotations: true
  remove_visible_parameter_annotations: true
  remove_visible_type_annotations: true
optimizer:
  inline_goto_goto: true
  inline_goto_return: true
  remove_nops: true
compression_level: 9
dictionary: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
randomized_string_length: 1
libraries:
  - "C:/Program Files/Java/jre1.8.0_201/lib/rt.jar"
exclusions:
  - "!renamer: me/itzsomebody/counter/Counter.*"
```

**Relevant errors:** None (just hangs).

**Reproduction steps:**
1. Set an exclusion(s) which limits renamer to certain classes.
2. Wait until it hangs on "Applying mappings"
